[versions]
androidGradlePlugin = "8.13.2"
androidxTestExtJunitKtx = "1.3.0"
androidxTestRunner = "1.7.0"
appcompat = "1.7.1"
# noinspection GradleDependency The last Compose BOM version that supports Kotlin 1.9.x
composeBom = "2023.10.00"
# See the table here for matching Kotlin version with Compose Compiler version
# https://developer.android.com/jetpack/androidx/releases/compose-kotlin#pre-release_kotlin_compatibility
composeCompiler = "1.5.15"
constraintlayout = "2.2.1"
coreKtx = "1.17.0"
dokka = "2.1.0"
dropshots = "0.5.1"
fragmentKtx = "1.8.9"
gradleGitVersion = "4.2.0"
# noinspection NewerVersionAvailable Last version that supports Kotlin 1.9.x
kotest = "5.9.1"
# Sticking with Kotlin 1.9.x for now for maximum compatibility.
# Not all projects use 2.x+ yet, and forcing an upgrade can increase client DEX sizes.
# noinspection NewerVersionAvailable
kotlin = "1.9.25"
# noinspection NewerVersionAvailable Last version that supports Kotlin 1.9.x
kotlinxCoroutinesTest = "1.8.1"
leakCanary = "2.14"
lifecycle = "2.9.4"
material = "1.13.0"
# noinspection NewerVersionAvailable Last version that supports Kotlin 1.9.x
mockk = "1.14.2"
# noinspection NewerVersionAvailable Last version that supports Kotlin 1.9.x
rebugger = "1.0.0-rc03"
relinker = "1.4.5"
startup = "1.2.0"
testExtJunit = "1.3.0"
vanniktechPublish = "0.35.0"
volley = "1.2.1"

[libraries]
android-volley = { module = "com.android.volley:volley", version.ref = "volley" }
androidx-activity-compose = { module = "androidx.activity:activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-android = { module = "androidx.compose.ui:ui-android" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-tooling-preview-android = { module = "androidx.compose.ui:ui-tooling-preview-android" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "testExtJunit" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidxTestExtJunitKtx" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
rebugger = { module = "io.github.theapache64:rebugger", version.ref = "rebugger" }
relinker = { module = "com.getkeepsafe.relinker:relinker", version.ref = "relinker" }
rive-android-preview = { module = "app.rive:rive-android", version = "+" }

[plugins]
allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
git-version = { id = "com.palantir.git-version", version.ref = "gradleGitVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechPublish" }
dropshots = { id = "com.dropbox.dropshots", version.ref = "dropshots" }
